## Release Build Pipeline - Build master and push to release-candidate channel
resources:
  repositories:
    - repository: templates
      type: BitBucket
      endpoint: "Bitbucket - spydersoft"
      name: spydersoftteam/azure-devops-templates

variables:
  - group: helm-repository
  - name: DOCKER_BUILDKIT
    value: 1
  - name: BUILD_CONFIGURATION
    value: "Release"
  - name: dockerImageName
    value: spydersoft/ha/unifi.ipmanager
  - name: containerRegistryName
    value: proget_docker
  - name: containerRegistryUrl
    value: proget.mattgerega.com
  - name: dockerImageFileName
    value: unifi_ipmanager
  - name: helmChartName
    value: unifi-ipmanager
  - name: helmChartPath
    value: $(Build.SourcesDirectory)/charts/unifi-ipmanager
  - name: artifactName
    value: unifiIpManager
  - name: artifactZipName
    value: unifi.ipmanager
  - name: npmInstallFolder
    value: $(Build.SourcesDirectory)/unifi.ipmanager
  - name: gulpFolder
    value: $(Build.SourcesDirectory)/unifi.ipmanager
  - name: publishProject
    value: unifi.ipmanager/unifi.ipmanager.csproj

trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - README.md

pr: none

stages:
- stage: Build
  jobs:
  - job: BuildJob
    pool:
      name: Default
      demands: agent.os -equals Linux
    steps:
    - template: step_collections/dotnet-api-build-steps.yml@templates
      parameters:
        publishProject: $(publishProject)
    # this code takes all the files in $(Build.ArtifactStagingDirectory) and uploads them as an artifact of your pipeline.
    - publish: '$(Build.ArtifactStagingDirectory)' 
      artifact: '$(artifactName)'

- stage: docker_publish
  displayName: Create Docker Image
  jobs:
  - template: jobs/docker-image-job.yml@templates
    parameters:
      dockerImageName: $(dockerImageName)
      containerRegistryName: $(containerRegistryName)
      containerRegistryUrl: $(containerRegistryUrl)
      artifactName: '$(artifactName)'
      artifactZipName: $(artifactZipName)
      dockerImageFileName: $(dockerImageFileName)
        

- stage: helm_publish
  displayName: Publish Helm Chart
  jobs:
  - job: create_helm_chart_and_publish
    pool:
      name: Default
      demands: agent.os -equals Linux
    steps:
    - task: CmdLine@2
      inputs:
        script: |
         helm package . --app-version $(build.buildnumber) --version $(build.buildnumber) -u
         curl $(helm_repository_url) --user $(helm_username):$(helm_password) --upload-file $(helmChartName)-$(build.buildnumber).tgz
        workingDirectory: $(helmChartPath)

- stage: stage_release
  dependsOn:
  - helm_publish
  displayName: Create and Deploy Octopus Release to Release Candidate Channel
  jobs:
  - deployment: stage
    displayName: 'Deploy to Stage'
    environment: stage
    pool:
      name: Default
      demands: agent.os -equals Linux
    strategy:
      runOnce:
        deploy:
          steps:
          - task: OctopusCreateRelease@4
            inputs:
              OctoConnectedServiceName: 'octopus-mattgerega-com'
              Space: 'Gerega' #'Spaces-1'
              ProjectGroup: 'Home Automation' 
              ProjectName: 'unifi.ipmanager.k8' 
              ReleaseNumber: '$(build.buildnumber)'
              Channel: 'release-candidate' #'Channels-281'
              DeployToEnvironment: 'mattgerega.org (Staging)' #'Environments-1'
              AdditionalArguments: '--packageversion $(build.buildnumber)'
   
- stage: production_release
  dependsOn:
  - stage_release
  displayName: Promote to Production
  jobs:
  - deployment: production
    displayName: 'Promote to Production'
    environment: production
    pool:
      name: Default
      demands: agent.os -equals Linux
    strategy:
      runOnce:
        deploy:
          steps:
          - task: OctopusPromote@4
            inputs:
              OctoConnectedServiceName: 'octopus-mattgerega-com'
              Space: 'Gerega' #'Spaces-1'
              ProjectGroup: 'Home Automation' 
              ProjectName: 'unifi.ipmanager.k8' 
              Project: 'unifi.ipmanager.k8'
              From: 'mattgerega.org (Staging)' #'Environments-2'
              To: 'mattgerega.com (Production)' #'Environments-3'

