sonar.projectKey=spyder007_unifi-ipmanager-react-ui
sonar.javascript.lcov.reportPaths=./frontend/output/coverage/lcov.info
sonar.sources=./frontend/src/
sonar.exclusions=**/frontend/src/api/**/*
sonar.test.inclusions=**/frontend/src/**/*.test.tsx
sonar.scanner.scanAll=false
