## Build Pipeline - Build, publish container image, and update helmfile config
resources:
  repositories:
    - repository: templates
      type: github
      endpoint: spydersoft-gh
      name: spydersoft-consulting/azure-devops-templates
    - repository: helmfileconfig
      type: github
      endpoint: spydersoft-gh
      name: spyder007/ha-helm-config

trigger:
  branches:
    include:
      - main
      - feature/*
  paths:
    exclude:
      - README.md

pr: none

extends:
  template: stages/stages-build-docker-update-helm/v1.yml@templates
  parameters:
    buildProject: Unifi.IpManager.sln
    publishProject: Unifi.IpManager/Unifi.IpManager.csproj
    artifactName: unifiIpManager
    artifactZipName: Unifi.IpManager
    dockerImageFileName: unifi_ipmanager
    dockerImageName: spydersoft/ha/unifi.ipmanager
    imageTagVariableName: unifi_ipmanager
    helmfileRepoName: helmfileconfig
    execute_sonar: true
    execute_tests: true
    test_projects: '**/*.Tests/*.csproj'
    use_sonarcloud: true
    sonar_cloud_organization: spydersoft-mjg
    sonar_endpoint_name: sonarcloud-spydersoft
    sonar_project_name: unifi-ipmanager
    sonar_project_key: spyder007_unifi-ipmanager

    