## Build Pipeline - Build, publish container image, and update helmfile config
resources:
  repositories:
    - repository: templates
      type: github
      endpoint: spydersoft-gh
      name: spydersoft-consulting/azure-devops-templates
    - repository: helmfileconfig
      type: github
      endpoint: spydersoft-gh
      name: spyder007/ha-helm-config

trigger:
  branches:
    include:
      - main
      - feature/*
  paths:
    exclude:
      - README.md

pr:
  branches:
    include:
      - main

extends:
  template: pipelines/build-api/v1.yml@templates
  parameters:
    buildProject: Unifi.IpManager.sln
    publishProject: Unifi.IpManager/Unifi.IpManager.csproj
    netCoreVersion: '8.0.x'
    artifactName: unifiIpManager
    artifactZipName: Unifi.IpManager
    containerRegistryName: github-spydersoft-docker
    dockerFilePath: Dockerfile.simple
    dockerImageName: spyder007/unifi-ipmanager
    imageTagVariableName: unifi_ipmanager
    helmfileRepoName: helmfileconfig
    executeSonar: true
    externalFeedCredentials: SpydersoftGithub
    ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
      updateHelmConfig: false
      buildAndPublishDockerImage: false
    ${{ else }}:
      updateHelmConfig: true
      buildAndPublishDockerImage: true
    sonar_EndpointName: sonarcloud-spydersoft
    sonarProjectKey: spyder007_unifi-ipmanager
    sonarProjectName: unifi-ipmanager
    executeTests: true
    testProjects: '**/*.Tests/*.csproj'
    useSonarCloud: true
    sonarCloudOrganization: spydersoft-mjg

    