## Build Pipeline - Build, publish container image, and update helmfile config
resources:
  repositories:
    - repository: templates
      type: BitBucket
      endpoint: "Bitbucket - spydersoft"
      name: spydersoftteam/azure-devops-templates
    - repository: helmfileconfig
      type: BitBucket
      endpoint: Bitbucket - spydersoft
      name: spydersoftteam/ha-helm-app-config

trigger:
  branches:
    include:
      - main
      - feature/*
  paths:
    exclude:
      - README.md

pr: none

extends:
  template: stages/stages-build-docker-update-helm/v1.yml@templates
  parameters:
    buildProject: unifi.ipmanager.sln
    publishProject: unifi.ipmanager/unifi.ipmanager.csproj
    artifactName: unifiIpManager
    artifactZipName: unifi.ipmanager
    dockerImageFileName: unifi_ipmanager
    dockerImageName: spydersoft/ha/unifi.ipmanager
    imageTagVariableName: unifi_ipmanager
    helmfileRepoName: helmfileconfig
    execute_sonar: ${{ eq(variables['Build.SourceBranch'], 'refs/heads/main') }}
    sonar_endpoint_name: sonarqube
    sonar_project_name: unifi.ipmanager
    sonar_project_key: Home_Automation_Home_Automation_AYV-PxRymblgg6j_jAeI
    execute_tests: true