## Build Pipeline - Build, publish container image, and update helmfile config
resources:
  repositories:
    - repository: templates
      type: github
      endpoint: spydersoft-gh
      name: spydersoft-consulting/azure-devops-templates
    - repository: helmfileconfig
      type: github
      endpoint: spydersoft-gh
      name: spyder007/ha-helm-config

trigger:
  branches:
    include:
      - main
      - feature/*
  paths:
    exclude:
      - README.md

pr:
  branches:
    include:
      - main

extends:
  template: pipelines/build-api/v1.yml@templates
  parameters:
    buildProject: Unifi.IpManager.sln
    publishProject: Unifi.IpManager/Unifi.IpManager.csproj
    netCoreVersion: '8.0.x'
    artifactName: unifiIpManager
    artifactZipName: Unifi.IpManager
    dockerFilePath: unifi_ipmanager
    dockerImageName: spydersoft/ha/unifi.ipmanager
    imageTagVariableName: unifi_ipmanager
    helmfileRepoName: helmfileconfig
    execute_sonar: true
    ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
      updateHelmConfig: false
      buildAndPublishDockerImage: false
    ${{ else }}:
      updateHelmConfig: true
      buildAndPublishDockerImage: true
    sonar_endpoint_name: sonarcloud-spydersoft
    sonar_project_key: spyder007_unifi-ipmanager
    sonar_project_name: unifi-ipmanager
    execute_tests: true
    test_projects: '**/*.Tests/*.csproj'
    use_sonarcloud: true
    sonar_cloud_organization: spydersoft-mjg

    